sudo: false

dist: trusty

language: php

php:
  - nightly
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: nightly
  include:
    - php: "5.3"
      dist: precise

before_script:
  - composer install --no-interaction

script:
  - composer cover
  - composer check-style

after_script:
  - composer coveralls
